version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: abode_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: abode
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: abode_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata: