version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: abode_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: abode
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: abode_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
    container_name: abode_worker
    restart: unless-stopped
    command: npx ts-node src/jobs/addressLookupJob.ts
    depends_on:
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/abode
      - REDIS_HOST=redis

  backend:
    build:
      context: .
    container_name: abode_backend
    restart: unless-stopped
    command: npm run dev
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/abode
      - REDIS_HOST=redis

volumes:
  pgdata: